version: '3.1'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 9000:9000
    volumes:
      - ./client/:/client/
      - /client/node_modules/
    command: npm run dev

  server:
    environment:
      HTTP_PORT: 80
      MPD_HOST: ${MPD_HOST}
      MPD_PORT: ${MPD_PORT}
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
      - 9229:9229
    volumes:
      - ./server/:/server/
      - /server/build/
      - /server/node_modules/
    command: npm run dev
