version: '3.1'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 9000:9000
    volumes:
      - ./client/src/:/client/src/
    command: npm run dev

  server:
    environment:
      HTTP_PORT: 80
      MPD_HOST: mpd
      MPD_PORT: 6600
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
      - 9229:9229
    volumes:
      - ./server/src/:/server/src/
    command: npm run dev

  mpd:
    build:
      context: ./mpd
    volumes:
      - .mpd/cache:/mpd/cache
      - .mpd/playlists:/mpd/playlists
      - .mpd/music:/mpd/music
    devices:
      - /dev/snd:/dev/snd
    # ports:
    #   - ${DC_MPD_PORT}:6600
    restart: unless-stopped
